export const SET_LOADING = 'SET_LOADING'
export const SET_CATEGORY = 'SET_CATEGORY'
export const TARGET_CATEGORY = "TARGET_CATEGORY"
export const SET_LIST_COCTAILS = 'SET_LIST_COCTAILS'
export const SET_SINGLE_COCTAIL = "SET_SINGLE_COCTAIL"
export const CLEAR_SINGLE_COCTAIL = "SINGLE_COCTAIL_REMOVE"
export const SET_COMMENT_USER = "SET_COMMENT_USER"
export const SET_COMMENT_TEXT = "SET_COMMENT_TEXT"

export const PUSH_COMMENT = "PUSH_COMMENT"

export const CLOSE_MODAL = "CLOSE_MODAL"
export const OPEN_MODAL = "OPEN_MODAL"
export const REMOVE_COMMENT = "REMOVE_COMMENT"







